### ISSUE TITLE
Router doesn't behave properly on mobile end 

### ISSUE THREAD

**Issue by Izzy1647** [ghy99123/NextBlog#1]
### Issue
Can't properly go back to the last page sometimes.

### Env
Safari on IOS

**Comment by ghy99123** [comment]
可能是因为锚点定位的关系，已修复

**Comment by ghy99123** [comment]
> ### Issue
> Can't properly go back to the last page sometimes.
> 
> ### Env
> Safari on IOS

可能是因为锚点定位的关系，已修复

**Comment by ghy99123** [comment]
> ### Issue
> Can't properly go back to the last page sometimes.
> 
> ### Env
> Safari on IOS
